spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

rabbitmq:
  exchange: imitationTrucks
  routingKey: myRoutingKey
  queue:
    name: truckCordsQueue
    durable: false
    exclusive: false