FROM maven:3.8-openjdk-17 AS MAVEN_BUILD
EXPOSE 8081
WORKDIR java
COPY ./ ./
RUN mvn clean package -DskipTests



FROM akoskuczi/openjdk-11
COPY --from=MAVEN_BUILD java/target/imitation-truck-1.0.jar out/imitation-truck.jar

CMD ["java", "-jar","-Dspring.profiles.active=docker", "out/imitation-truck.jar"]

