server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/truck_microservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


rabbitmq:
  exchange: imitationTrucks
  routingKey: myRoutingKey
  queue:
    name: truckCordsQueue
    durable: true
    exclusive: false

scheduler-time:
  service:
    truck-service: 300
    checking-truck-coordinates-service: 300

logging:
  level:
    root: error
