server:
  port: 8081

spring:
  rabbitmq:
    #host: localhost
    host: host.docker.internal
    port: 5672
    stream:
      username: guest
      password: guest
  datasource:
      #url: jdbc:postgresql://host.docker.internal:5432/truck_microservice
      url: jdbc:postgresql://localhost:5432/truck_microservice
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver



rabbitmq:
  receive:
    exchange: imitationTrucks
    routing-key: myRoutingKey
    queue:
      name: truckCordsQueue
      durable: true
      exclusive: false
  send:
    exchange: truck-follower
    routing-key: myRoutingKey
    queue:
      name: sendAlarmQueue
      durable: true
      exclusive: false


scheduler-time:
  service:
    truck-service: 300
    checking-truck-coordinates-service: 300

services:
  alarm-service:
    thread-pool-amount: 4

logging:
  level:
    root: info

