server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  datasource:
      url: jdbc:postgresql://localhost:5433/truck_microservice
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
  profiles:
    active: personal

rabbitmq:
  exchange: truck-follower
  routing-key: myRoutingKey
  queue:
    name: sendAlarmQueue
    durable: true
    exclusive: false

logging:
  level:
    root: info

telegram:
  bot:
    token: ${TELEGRAM_TOKEN}
    name: ${TELEGRAM_NAME}
